"""initial: insurer/product/version/document/clause_chunks

Revision ID: e9ae743aa223
Revises: 
Create Date: 2026-05-22 15:37:21.299057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ae743aa223'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('homepage_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('insurer_id', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("area IN ('auto','accident_disease','fire')", name='ck_products_area'),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_insurer_id'), ['insurer_id'], unique=False)

    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=120), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'valid_from', name='uq_versions_product_valid_from')
    )
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_versions_product_id'), ['product_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("doc_type IN ('summary','business','terms')", name='ck_documents_doc_type'),
    sa.ForeignKeyConstraint(['version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'doc_type', name='uq_documents_version_doc_type')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_version_id'), ['version_id'], unique=False)

    op.create_table('clause_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_type', sa.String(length=16), nullable=False),
    sa.Column('clause_no', sa.String(length=64), nullable=True),
    sa.Column('sub_no', sa.String(length=32), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("chunk_type IN ('article','paragraph','item','table','annex','other')", name='ck_chunks_chunk_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['clause_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clause_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_chunks_clause', ['document_id', 'clause_no'], unique=False)
        batch_op.create_index('idx_chunks_document', ['document_id'], unique=False)
        batch_op.create_index('idx_chunks_parent', ['parent_chunk_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clause_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_chunks_parent')
        batch_op.drop_index('idx_chunks_document')
        batch_op.drop_index('idx_chunks_clause')

    op.drop_table('clause_chunks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_version_id'))

    op.drop_table('documents')
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_versions_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_versions_is_active'))

    op.drop_table('product_versions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_insurer_id'))
        batch_op.drop_index(batch_op.f('ix_products_area'))

    op.drop_table('products')
    op.drop_table('insurers')
    # ### end Alembic commands ###
